//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.BmiServiceSoap")]
    public interface BmiServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bmi", ReplyAction="*")]
        double bmi(double height, double weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bmi", ReplyAction="*")]
        System.Threading.Tasks.Task<double> bmiAsync(double height, double weight);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BmiServiceSoapChannel : WebApplication1.ServiceReference1.BmiServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BmiServiceSoapClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.BmiServiceSoap>, WebApplication1.ServiceReference1.BmiServiceSoap {
        
        public BmiServiceSoapClient() {
        }
        
        public BmiServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BmiServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BmiServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BmiServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double bmi(double height, double weight) {
            return base.Channel.bmi(height, weight);
        }
        
        public System.Threading.Tasks.Task<double> bmiAsync(double height, double weight) {
            return base.Channel.bmiAsync(height, weight);
        }
    }
}
